drop table sdwa_site_visits if exists cascade;

CREATE TABLE sdwa_site_visits (
	"SUBMISSIONYEARQUARTER" VARCHAR, 
	"PWSID" DECIMAL, 
	"VISIT_ID" DECIMAL, 
	"VISIT_DATE" DATE, 
	"AGENCY_TYPE_CODE" VARCHAR, 
	"VISIT_REASON_CODE" VARCHAR, 
	"MANAGEMENT_OPS_EVAL_CODE" TEXT, 
	"SOURCE_WATER_EVAL_CODE" VARCHAR, 
	"SECURITY_EVAL_CODE" TEXT, 
	"PUMPS_EVAL_CODE" TEXT, 
	"OTHER_EVAL_CODE" VARCHAR, 
	"COMPLIANCE_EVAL_CODE" TEXT, 
	"DATA_VERIFICATION_EVAL_CODE" TEXT, 
	"TREATMENT_EVAL_CODE" TEXT, 
	"FINISHED_WATER_STOR_EVAL_CODE" VARCHAR, 
	"DISTRIBUTION_EVAL_CODE" TEXT, 
	"FINANCIAL_EVAL_CODE" VARCHAR, 
	"VISIT_COMMENTS" VARCHAR, 
	"FIRST_REPORTED_DATE" DATE, 
	"LAST_REPORTED_DATE" TEXT
);

\copy sdwa_site_visits from 'data/sdwa_site_visits.csv' csv header;
