drop table if exists sdwa_pub_water_systems cascade;

CREATE TABLE sdwa_pub_water_systems (
	submissionyearquarter TEXT, 
	pwsid TEXT, 
	pws_name TEXT, 
	primacy_agency_code TEXT, 
	epa_region TEXT, 
	season_begin_date TEXT, 
	season_end_date TEXT, 
	pws_activity_code TEXT, 
	pws_deactivation_date DATE, 
	pws_type_code TEXT, 
	dbpr_schedule_cat_code TEXT, 
	cds_id TEXT, 
	gw_sw_code TEXT, 
	lt2_schedule_cat_code TEXT, 
	owner_type_code TEXT, 
	population_served_count TEXT, 
	pop_cat_2_code TEXT, 
	pop_cat_3_code TEXT, 
	pop_cat_4_code TEXT, 
	pop_cat_5_code TEXT, 
	pop_cat_11_code TEXT, 
	primacy_type TEXT, 
	primary_source_code TEXT, 
	is_grant_eligible_ind TEXT, 
	is_wholesaler_ind TEXT, 
	is_school_or_daycare_ind TEXT, 
	service_connections_count TEXT, 
	submission_status_code TEXT, 
	org_name TEXT, 
	admin_name TEXT, 
	email_addr TEXT, 
	phone_number TEXT, 
	phone_ext_number TEXT, 
	fax_number TEXT, 
	alt_phone_number TEXT, 
	address_line1 TEXT, 
	address_line2 TEXT, 
	city_name TEXT, 
	zip_code TEXT, 
	country_code TEXT, 
	first_reported_date DATE, 
	last_reported_date DATE, 
	state_code TEXT, 
	source_water_protection_code TEXT, 
	source_protection_begin_date TEXT, 
	outstanding_performer TEXT, 
	outstanding_perform_begin_date TEXT, 
	reduced_rtcr_monitoring TEXT, 
	reduced_monitoring_begin_date TEXT, 
	reduced_monitoring_end_date TEXT, 
	seasonal_startup_system TEXT
);

\copy sdwa_pub_water_systems from 'data/sdwa_pub_water_systems.csv' csv header;
