drop table if exists sdwa_site_visits cascade;

CREATE TABLE sdwa_site_visits (
	"SUBMISSIONYEARQUARTER" TEXT, 
	"PWSID" TEXT, 
	"VISIT_ID" TEXT, 
	"VISIT_DATE" DATE, 
	"AGENCY_TYPE_CODE" TEXT, 
	"VISIT_REASON_CODE" TEXT, 
	"MANAGEMENT_OPS_EVAL_CODE" TEXT, 
	"SOURCE_WATER_EVAL_CODE" TEXT, 
	"SECURITY_EVAL_CODE" TEXT, 
	"PUMPS_EVAL_CODE" TEXT, 
	"OTHER_EVAL_CODE" TEXT, 
	"COMPLIANCE_EVAL_CODE" TEXT, 
	"DATA_VERIFICATION_EVAL_CODE" TEXT, 
	"TREATMENT_EVAL_CODE" TEXT, 
	"FINISHED_WATER_STOR_EVAL_CODE" TEXT, 
	"DISTRIBUTION_EVAL_CODE" TEXT, 
	"FINANCIAL_EVAL_CODE" TEXT, 
	"VISIT_COMMENTS" TEXT, 
	"FIRST_REPORTED_DATE" DATE, 
	"LAST_REPORTED_DATE" TEXT
);

\copy sdwa_site_visits from 'data/sdwa_site_visits.csv' csv header;
