drop table if exists sdwa_lcr_samples cascade;

CREATE TABLE sdwa_lcr_samples (
	"SUBMISSIONYEARQUARTER" TEXT, 
	"PWSID" TEXT, 
	"SAMPLE_ID" TEXT, 
	"SAMPLING_END_DATE" DATE, 
	"SAMPLING_START_DATE" DATE, 
	"RECONCILIATION_ID" TEXT, 
	"SAMPLE_FIRST_REPORTED_DATE" DATE, 
	"SAMPLE_LAST_REPORTED_DATE" DATE, 
	"SAR_ID" TEXT, 
	"CONTAMINANT_CODE" TEXT, 
	"RESULT_SIGN_CODE" TEXT, 
	"SAMPLE_MEASURE" TEXT, 
	"UNIT_OF_MEASURE" TEXT, 
	"SAR_FIRST_REPORTED_DATE" DATE, 
	"SAR_LAST_REPORTED_DATE" DATE
);

\copy sdwa_lcr_samples from 'data/sdwa_lcr_samples.csv' csv header;
